baseURL = 'https://alpha.is-a.dev'
languageCode = 'fi'
title = 'YouFoundAlpha'
theme = ["hugo-redirect", "PaperMod"]

[params.profileMode]
enabled = true
subtitle = "I code mostly in [Node.JS](https://nodejs.org/)"
imageUrl = "/pfp.png"
imageTitle = "My picture"
imageWidth = 240
imageHeight = 240
[params]
hideFooter = true
defaultTheme = "dark"
disableThemeToggle = true
description = 'Small backend developer'
[[params.socialIcons]]
name = "email"
url = "mailto:alpha@alpha.is-a.dev"
[[params.socialIcons]]
name = "pgpkey"
url = "https://alpha.is-a.dev/gpg"
[social.twitter]
card = "summary_large_image"
url = "https://alpha.is-a.dev"
title = "YouFoundAlpha"
description = "Small backend developer"
image = "https://avatars.githubusercontent.com/u/86548581"
[social.og]
type = "website"
url = "https://alpha.is-a.dev"
title = YouFoundAlpha"
description = "Small backend developer"
image = "https://avatars.githubusercontent.com/u/86548581"
[params.assets]
  favicon = "https://alpha.is-a.dev/favicon.ico"
  favicon16x16 = "https://alpha.is-a.dev/favicon-16x16.png"
  favicon32x32 = "https://alpha.is-a.dev/favicon-32x32.png"
  apple_touch_icon = "https://alpha.is-a.dev/apple_touch_icon.png"
  safari_pinned_tab = "https://alpha.is-a.dev/safari_pinned_tab.svg"
[analytics.google]
SiteVerificationTag = "BsDZvqMslxbaCC-BCMBj4mOyIbuAr2Oos4jECFJS5y8"
[params.minify]
    disableXML = true
    minifyOutput = true




