baseURL = 'https://alpha.is-a.dev'
languageCode = 'fi'
title = 'YouFoundAlpha'
theme = ["hugo-redirect", "PaperMod"]
env = "production"
[params.profileMode]
enabled = true
subtitle = "I code mostly in [Node.JS](https://nodejs.org/)"
imageUrl = "https://cdn-a12.pages.dev/pfp.png"
imageTitle = "My picture"
imageWidth = 240
imageHeight = 240
[params]
hideFooter = true
defaultTheme = "dark"
disableThemeToggle = true
description = 'Small backend developer'
enableRobotsTXT = true
[params.analytics.google]
SiteVerificationTag = "K6i2mlq9VlR56vVe6ULpkuqsoKlIDORPYJ6uVjH3iz8"
[[params.socialIcons]]
name = "gitlab"
url = "https://gitlab.com/YouFoundAlpha"
[[params.socialIcons]]
name = "github"
url = "https://github.com/YouFoundAlpha"
[social.twitter]
card = "summary_large_image"
url = "https://alpha.is-a.dev"
title = "YouFoundAlpha"
description = "Small backend developer"
image = "https://cdn-a12.pages.dev/pfp.png"
[social.og]
type = "website"
url = "https://alpha.is-a.dev"
title = "YouFoundAlpha"
description = "Small backend developer"
image = "https://cdn-a12.pages.dev/pfp.png"
[params.assets]
  favicon = "https://cdn-a12.pages.dev/favicon.ico"
  favicon16x16 = "https://cdn-a12.pages.dev/favicon-16x16.png"
  favicon32x32 = "https://cdn-a12.pages.dev/favicon-32x32.png"
  apple_touch_icon = "https://cdn-a12.pages.dev/apple_touch_icon.png"
  safari_pinned_tab = "https://cdn-a12.pages.dev/safari_pinned_tab.svg"
[params.minify]
    disableXML = true
    minifyOutput = true
    [sitemap]
  changeFreq = 'always'
  filename = 'sitemap.xml'
  priority = -1



