baseURL = 'https://alpha.is-a.dev'
languageCode = 'fi'
title = 'YouFoundAlpha'
theme = ["hugo-redirect", "PaperMod"]

[params.profileMode]
enabled = true
subtitle = "I code mostly in Node.JS"
imageUrl = "https://avatars.githubusercontent.com/u/86548581?v=4"
imageTitle = "My picture"
imageWidth = 128
imageHeight = 128
[params]
hideFooter = true
defaultTheme = "dark"
disableThemeToggle = true
[[params.socialIcons]]
name = "x"
url = "https://alpha.is-a.dev/x"

[[params.socialIcons]]
name = "twitch"
url = "https://alpha.is-a.dev/twitch"
[[params.socialIcons]]
name = "kick"
url = "https://alpha.is-a.dev/kick"
[analytics.google]
SiteVerificationTag = "BsDZvqMslxbaCC-BCMBj4mOyIbuAr2Oos4jECFJS5y8"



