baseURL = 'https://alpha.is-a.dev'
languageCode = 'fi'
title = 'YouFoundAlpha'
theme = ["hugo-redirect", "PaperMod"]
[params.profileMode]
enabled = true
subtitle = "I code mostly in [Node.JS](https://nodejs.org/)"
imageUrl = "https://cdn-a12.pages.dev/web/icons/pfp.png"
imageTitle = "My picture"
imageWidth = 240
imageHeight = 240
[params]
hideFooter = true
defaultTheme = "dark"
disableThemeToggle = true
description = 'Small backend developer'
enableRobotsTXT = true
[params.analytics.google]
SiteVerificationTag = "K6i2mlq9VlR56vVe6ULpkuqsoKlIDORPYJ6uVjH3iz8"
[[params.socialIcons]]
name = "gitlab"
url = "https://gitlab.com/YouFoundAlpha"
[[params.socialIcons]]
name = "github"
url = "https://github.com/YouFoundAlpha"
[[params.socialIcons]]
name = "x"
url = "https://x.com/YouFoundAlpha"
[[params.socialIcons]]
name = "youtube"
url = "https://youtube.com/@YouFoundAlpha"
[[params.socialIcons]]
name = "mastodon"
url = "https://mastodon.social/@YouFoundAlpha"
[[params.socialIcons]]
name = "email"
url = "mailto:alpha@alpha.is-a.dev"
[[params.socialIcons]]
name = "key"
url = "https://cdn-a12.pages.dev/web/static/key.asc"
[[params.socialIcons]]
name = "discord"
url = "https://discord.com/users/661121998830960651"

[social.twitter]
card = "summary_large_image"
url = "https://alpha.is-a.dev"
title = "YouFoundAlpha"
description = "Small backend developer"
image = "https://media.istockphoto.com/id/146882475/photo/exploding-keyboard.jpg?s=612x612&w=0&k=20&c=27Z1Lw5K3UZDrhjat0W8iEhMkwWAI7Y6VyTHs7R6XaM="
[social.og]
type = "website"
url = "https://alpha.is-a.dev"
title = "YouFoundAlpha"
description = "Small backend developer"
image = "https://media.istockphoto.com/id/146882475/photo/exploding-keyboard.jpg?s=612x612&w=0&k=20&c=27Z1Lw5K3UZDrhjat0W8iEhMkwWAI7Y6VyTHs7R6XaM="
[params.assets]
  favicon = "https://cdn-a12.pages.dev/web/icons/favicon.ico"
  favicon16x16 = "https://cdn-a12.pages.dev/web/icons/favicon-16x16.png"
  favicon32x32 = "https://cdn-a12.pages.dev/web/icons/favicon-32x32.png"
  apple_touch_icon = "https://cdn-a12.pages.dev/web/icons/apple_touch_icon.png"
  safari_pinned_tab = "https://cdn-a12.pages.dev/web/icons/safari_pinned_tab.svg"
[params.minify]
    disableXML = true
    minifyOutput = true
    [sitemap]
  changeFreq = 'always'
  filename = 'sitemap.xml'
  priority = -1



